# Default values for cnj-security-oidc-backend-spring.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: docker.at41tools.k8s.aws.msgoat.eu/cloudtrain/cnj-security-oidc-backend-spring
  tag: ${project.version}
  pullPolicy: IfNotPresent
#  pullSecret: fwp-pull-secret

probes:
  readiness:
    path: /actuator/health
  liveness:
    path: /actuator/health

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    traefik.frontend.rule.type: PathPrefixStrip
  hosts:
    - host: "${k8s.ingress.host}"
      paths: ["${k8s.ingress.path}"]

resources:
  limits:
    #   cpu: 100m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 756Mi

nodeSelector: {}

tolerations: []

affinity: {}

# Keycloak Open ID Connect Provider configuration
oidc:
  jwt:
    jwtSetUri: https://iam.at41tools.k8s.aws.msgoat.eu/auth/realms/cloudtrain/protocol/openid-connect/certs
