apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cnj-security-oidc-backend-quarkus.fullname" . }}
  labels:
    {{- include "cnj-security-oidc-backend-quarkus.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "cnj-security-oidc-backend-quarkus.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cnj-security-oidc-backend-quarkus.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.liveness.path }}
              port: http
            initialDelaySeconds: 60
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readiness.path }}
              port: http
            initialDelaySeconds: 15
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: MP_JWT_VERIFY_PUBLICKEY_LOCATION
              value: {{ .Values.security.oidc.jwksUri | quote }}
            - name: MP_JWT_VERIFY_ISSUER
              value: {{ .Values.security.oidc.issuer | quote }}
{{- if .Values.image.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
{{- end }}
{{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
