# Default values for cnj-security-oidc-backend-javaee.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ${docker.image.name}
  tag: ${project.version}
  pullPolicy: IfNotPresent

probes:
  readiness:
    path: /api/v1/probes/readiness
  liveness:
    path: /api/v1/probes/liveness

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    traefik.frontend.rule.type: PathPrefixStrip
  hosts:
    - host: "${k8s.ingress.host}"
      paths: ["${k8s.ingress.path}"]

resources:
  limits:
    #   cpu: 100m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 756Mi

nodeSelector: {}

tolerations: []

affinity: {}

# security configuration (MP JWT AUTH)
mp:
  jwt:
    verifyPublicKeyLocation: "https://iam.at41tools.k8s.aws.msgoat.eu/auth/realms/cloudtrain/protocol/openid-connect/certs"
    verifyIssuer: "https://iam.at41tools.k8s.aws.msgoat.eu/auth/realms/cloudtrain"