apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${project.artifactId}-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${project.artifactId}
  template:
    metadata:
      labels:
        app: ${project.artifactId}
    spec:
      containers:
        - name: ${project.artifactId}
          image: ${docker.image.name}
          imagePullPolicy: "Always"
          resources:
            limits:
              cpu: "0.5"
              memory: "1Gi"
          #            requests:
          #              cpu: "0.5"
          #              memory: "500Mi"
          ports:
            - name: http-port
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /api/v1/probes/liveness
              port: http-port
            initialDelaySeconds: 60
            periodSeconds: 60
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/v1/probes/readiness
              port: http-port
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
