apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ${project.artifactId}-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
spec:
  rules:
    - http:
        paths:
          - path: /${project.artifactId}
            backend:
              serviceName: ${project.artifactId}
              servicePort: 8080