apiVersion: v1
kind: Service
metadata:
  name: ${project.artifactId}
  labels:
    app: ${project.artifactId}
    tier: backend
    stage: local
spec:
  type: ClusterIP
  ports:
    - port: 8080
  selector:
    app: ${project.artifactId}
